companyweb/force-app/main/default/objects/account/fields/CW_VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>CW_VAT_Number__c</fullName>
    <description>VatNumber</description>
    <inlineHelpText>Accepted formats: &quot;869703978&quot;, &quot;0869 703 978&quot;, &quot;BE 0869.703.978&quot;, &quot;BE0869703978&quot;</inlineHelpText>
    <label>VAT Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt.object
<CustomObject>
    <label>Login Setup</label>
    <pluralLabel>Login Setups</pluralLabel>
</CustomObject>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Account_Activities_Field__c.field-meta.xml
<CustomField>
    <fullName>Account_Activities_Field__c</fullName>
    <inlineHelpText>Please, provide the API name of the existing Activities field on the Account object.
This mapping accepts Long Text Area fields only.</inlineHelpText>
    <label>Account Activities Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Account_Annual_Revenue_Field__c.field-meta.xml
<CustomField>
    <fullName>Account_Annual_Revenue_Field__c</fullName>
    <label>Account Annual Revenue Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Account_City_Field__c.field-meta.xml
<CustomField>
    <fullName>Account_City_Field__c</fullName>
    <label>Account City Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Account_CountryCode_Field__c.field-meta.xml
<CustomField>
    <fullName>Account_CountryCode_Field__c</fullName>
    <label>Account CountryCode Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Account_Credit_Limit_Field__c.field-meta.xml
<CustomField>
    <fullName>Account_Credit_Limit_Field__c</fullName>
    <inlineHelpText>Please, provide the API name of the existing Credit Limit field on the Account object.
This mapping accepts Number fields only.</inlineHelpText>
    <label>Account Credit Limit Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Account_Joint_Commitees_Field__c.field-meta.xml
<CustomField>
    <fullName>Account_Joint_Commitees_Field__c</fullName>
    <inlineHelpText>Please, provide the API name of the existing Joint Committees Blue Collar field on the Account object.
This mapping accepts Long Text Area fields only.</inlineHelpText>
    <label>Account Joint Commitees Blue Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Account_Joint_Commitees_White_Field__c.field-meta.xml
<CustomField>
    <fullName>Account_Joint_Commitees_White_Field__c</fullName>
    <inlineHelpText>Please, provide the API name of the existing Joint Committees White Collar field on the Account object.
This mapping accepts Long Text Area fields only.</inlineHelpText>
    <label>Account Joint Commitees White Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Account_Legal_Form_Field__c.field-meta.xml
<CustomField>
    <fullName>Account_Legal_Form_Field__c</fullName>
    <inlineHelpText>Please, provide the API name of the existing Legal Form field on the Account object.
This mapping accepts Picklist fields only.</inlineHelpText>
    <label>Account Legal Form Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Account_Main_Activity_Field__c.field-meta.xml
<CustomField>
    <fullName>Account_Main_Activity_Field__c</fullName>
    <inlineHelpText>Please, provide the API name of the existing Main Activity field on the Account object.
This mapping accepts Text and Long Text Area fields only.</inlineHelpText>
    <label>Account Main Activity Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Account_Number_Employees_Field__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_Employees_Field__c</fullName>
    <inlineHelpText>Please, provide the API name of the existing Number of Employees field on the Account object.
This mapping accepts Number fields only.</inlineHelpText>
    <label>Account Number Employees Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Account_Phone_Field__c.field-meta.xml
<CustomField>
    <fullName>Account_Phone_Field__c</fullName>
    <label>Account Phone Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Account_PostalCode_Field__c.field-meta.xml
<CustomField>
    <fullName>Account_PostalCode_Field__c</fullName>
    <label>Account PostalCode Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Account_Score_Field__c.field-meta.xml
<CustomField>
    <fullName>Account_Score_Field__c</fullName>
    <inlineHelpText>Please, provide the API name of the existing Company Web Score field on the Account object.
This mapping accepts Number fields only.</inlineHelpText>
    <label>Account Score Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Account_Social_Security_Field__c.field-meta.xml
<CustomField>
    <fullName>Account_Social_Security_Field__c</fullName>
    <inlineHelpText>Please, provide the API name of the existing Social Security Number field on the Account object.
This mapping accepts Text and Long Text Area fields only.</inlineHelpText>
    <label>Account Social Security Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Account_Street_Field__c.field-meta.xml
<CustomField>
    <fullName>Account_Street_Field__c</fullName>
    <label>Account Street Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Account_VAT_Number_Field__c.field-meta.xml
<CustomField>
    <fullName>Account_VAT_Number_Field__c</fullName>
    <inlineHelpText>Please, provide the API name of the existing VAT Number field on the Account object.
This mapping accepts Text and Long Text Area fields only.</inlineHelpText>
    <label>Account VAT Number Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/CW_CompanyWebLogin__c.field-meta.xml
<CustomField>
    <fullName>CW_CompanyWebLogin__c</fullName>
    <label>CompanyWebLogin</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/CW_CompanyWebPassword__c.field-meta.xml
<CustomField>
    <fullName>CW_CompanyWebPassword__c</fullName>
    <label>CompanyWebPassword</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/CW_CompanyWebSecret__c.field-meta.xml
<CustomField>
    <fullName>CW_CompanyWebSecret__c</fullName>
    <label>CompanyWebSecret</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/CW_Duplicate_Check_Creation__c.field-meta.xml
<CustomField>
    <fullName>CW_Duplicate_Check_Creation__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Enable/disable the VAT duplication rule on record creation</inlineHelpText>
    <label>Duplicate Check on Creation</label>
    <type>Checkbox</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/CW_Duplicate_Check_Refresh__c.field-meta.xml
<CustomField>
    <fullName>CW_Duplicate_Check_Refresh__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Enable/disable the VAT duplication rule on record refresh</inlineHelpText>
    <label>Duplicate Check on Refresh</label>
    <type>Checkbox</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/CW_ServiceIntegrator__c.field-meta.xml
<CustomField>
    <fullName>CW_ServiceIntegrator__c</fullName>
    <label>ServiceIntegrator</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Lead_Activities_Field__c.field-meta.xml
<CustomField>
    <fullName>Lead_Activities_Field__c</fullName>
    <inlineHelpText>Please, provide the API name of the existing Activities field on the Lead object.
This mapping accepts Long Text Area fields only.</inlineHelpText>
    <label>Lead Activities Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Lead_Annual_Revenue_Field__c.field-meta.xml
<CustomField>
    <fullName>Lead_Annual_Revenue_Field__c</fullName>
    <label>Lead Annual Revenue Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Lead_City_Field__c.field-meta.xml
<CustomField>
    <fullName>Lead_City_Field__c</fullName>
    <label>Lead City Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Lead_CountryCode_Field__c.field-meta.xml
<CustomField>
    <fullName>Lead_CountryCode_Field__c</fullName>
    <label>Lead CountryCode Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Lead_Credit_Limit_Field__c.field-meta.xml
<CustomField>
    <fullName>Lead_Credit_Limit_Field__c</fullName>
    <inlineHelpText>Please, provide the API name of the existing Credit Limit field on the Lead object.
This mapping accepts Number fields only.</inlineHelpText>
    <label>Lead Credit Limit Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Lead_Joint_Commitees_Field__c.field-meta.xml
<CustomField>
    <fullName>Lead_Joint_Commitees_Field__c</fullName>
    <inlineHelpText>Please, provide the API name of the existing Joint Committees field on the Lead object.
This mapping accepts Long Text Area fields only.</inlineHelpText>
    <label>Lead Joint Commitees Blue Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Lead_Joint_Commitees_White_Field__c.field-meta.xml
<CustomField>
    <fullName>Lead_Joint_Commitees_White_Field__c</fullName>
    <inlineHelpText>Please, provide the API name of the existing Joint Committees White Collar field on the Lead object.
This mapping accepts Long Text Area fields only.</inlineHelpText>
    <label>Lead Joint Commitees White Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Lead_Legal_Form_Field__c.field-meta.xml
<CustomField>
    <fullName>Lead_Legal_Form_Field__c</fullName>
    <inlineHelpText>Please, provide the API name of the existing Legal Form field on the Lead object.
This mapping accepts Picklist fields only.</inlineHelpText>
    <label>Lead Legal Form Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Lead_Main_Activity_Field__c.field-meta.xml
<CustomField>
    <fullName>Lead_Main_Activity_Field__c</fullName>
    <inlineHelpText>Please, provide the API name of the existing Main Activity field on the Lead object.
This mapping accepts Text and Long Text Area fields only.</inlineHelpText>
    <label>Lead Main Activity Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Lead_Number_Employees_Field__c.field-meta.xml
<CustomField>
    <fullName>Lead_Number_Employees_Field__c</fullName>
    <inlineHelpText>Please, provide the API name of the existing Number of Employees field on the Lead object.
This mapping accepts Number fields only.</inlineHelpText>
    <label>Lead Number Employees Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Lead_Phone_Field__c.field-meta.xml
<CustomField>
    <fullName>Lead_Phone_Field__c</fullName>
    <label>Lead Phone Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Lead_PostalCode_Field__c.field-meta.xml
<CustomField>
    <fullName>Lead_PostalCode_Field__c</fullName>
    <label>Lead PostalCode Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Lead_Score_Field__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score_Field__c</fullName>
    <inlineHelpText>Please, provide the API name of the existing Company Web Score field on the Lead object.
This mapping accepts Number fields only.</inlineHelpText>
    <label>Lead Score Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Lead_Social_Security_Field__c.field-meta.xml
<CustomField>
    <fullName>Lead_Social_Security_Field__c</fullName>
    <inlineHelpText>Please, provide the API name of the existing Social Security Number field on the Lead object.
This mapping accepts Text and Long Text Area fields only.</inlineHelpText>
    <label>Lead Social Security Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Lead_Street_Field__c.field-meta.xml
<CustomField>
    <fullName>Lead_Street_Field__c</fullName>
    <label>Lead Street Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/objects/CW_Login_Setup__mdt/fields/Lead_VAT_Number_Field__c.field-meta.xml
<CustomField>
    <fullName>Lead_VAT_Number_Field__c</fullName>
    <inlineHelpText>Please, provide the API name of the existing VAT Number field on the Lead object.
This mapping accepts Text and Long Text Area fields only.</inlineHelpText>
    <label>Lead VAT Number Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

companyweb/force-app/main/default/classes/companyWebAlertsTest.cls
@isTest
public class companyWebAlertsTest {

    @TestSetup
    public static void testSetup(){
        Account acc = new Account(Name='testacc', CW_VAT_Number__c='869703978');
        Lead lead = new Lead(LastName='testlead', Company='testacc', Status='Open - Not Contacted', CW_VAT_Number__c='869703978');
        insert acc;
        insert lead;
    }
    
    @isTest
    public static void companyWebAlertsAddCompanyToAlertsTest(){
        Test.setMock(WebServiceMock.class, new companyWebAddCompanyCallOutMock());
        CompanyWebController.addCompanyToAlerts('869703978');
    }
    
    @isTest
    public static void companyWebAlertsAddCompanyListToAlertsTest(){
        String accountId = [SELECT Id FROM ACCOUNT LIMIT 1].Id;
        Test.setMock(WebServiceMock.class, new companyWebAddCompanyListCallOutMock());
        CompanyWebController.addCompanyListToAlerts(new List<String>{ accountId });
    }

    @isTest
    public static void companyWebAlertsControllerTest(){
        CompanyWebAlertsController.invokeGetAlertsALaCarte();
    }
	
    @isTest
    public static void companyWebAlertsGetChangeDatesTest(){
        CW_Login_Setup__mdt oLoginSetup = new CW_Login_Setup__mdt();
        oLoginSetup = [SELECT Id, CW_CompanyWebLogin__c, CW_CompanyWebPassword__c, CW_CompanyWebSecret__c, CW_ServiceIntegrator__c, Account_VAT_Number_Field__c,
            Lead_VAT_Number_Field__c,Account_Score_Field__c,Account_Activities_Field__c,Account_Credit_Limit_Field__c,Account_Joint_Commitees_Field__c,
            Account_Joint_Commitees_White_Field__c,Account_Legal_Form_Field__c,Account_Main_Activity_Field__c,Account_Number_Employees_Field__c,
            Account_Social_Security_Field__c,Account_Phone_Field__c,Account_Street_Field__c,Account_PostalCode_Field__c,Account_City_Field__c,Account_CountryCode_Field__c,
            Account_Annual_Revenue_Field__c,CW_Duplicate_Check_Creation__c,
            CW_Duplicate_Check_Refresh__c,Lead_Score_Field__c,Lead_Activities_Field__c,Lead_Credit_Limit_Field__c,Lead_Joint_Commitees_Field__c,
            Lead_Joint_Commitees_White_Field__c,Lead_Legal_Form_Field__c,Lead_Main_Activity_Field__c,Lead_Number_Employees_Field__c,Lead_Social_Security_Field__c,
            Lead_Phone_Field__c,Lead_Annual_Revenue_Field__c,Lead_Street_Field__c,Lead_PostalCode_Field__c,Lead_City_Field__c,Lead_CountryCode_Field__c
            FROM CW_Login_Setup__mdt WHERE DeveloperName = 'CW_Login'];
        connectCompanywebBe.RequestStep1 request = new connectCompanywebBe.RequestStep1();
        request.CompanyWebLogin = oLoginSetup.CW_CompanyWebLogin__c;
        request.CompanyWebPassword = oLoginSetup.CW_CompanyWebPassword__c;
        request.ServiceIntegrator = oLoginSetup.CW_ServiceIntegrator__c;
        request.LoginHash = companyWebController.createCWLoginHash(oLoginSetup.CW_CompanyWebLogin__c, oLoginSetup.CW_CompanyWebPassword__c, oLoginSetup.CW_CompanyWebSecret__c);
        connectCompanywebBe.BasicHttpBinding_AlacarteServiceV1_6_soap httpreq = new connectCompanywebBe.BasicHttpBinding_AlacarteServiceV1_6_soap();
        
        Test.setMock(WebServiceMock.class, new companyWebGetChangedDatesCallOutMock());
        CompanyWebController.getChangeDates(httpreq, request);
    }
    
    @isTest
    public static void companyWebAlertsGetVatListTest(){
        CW_Login_Setup__mdt oLoginSetup = new CW_Login_Setup__mdt();
        oLoginSetup = [SELECT Id, CW_CompanyWebLogin__c, CW_CompanyWebPassword__c, CW_CompanyWebSecret__c, CW_ServiceIntegrator__c, Account_VAT_Number_Field__c,
            Lead_VAT_Number_Field__c,Account_Score_Field__c,Account_Activities_Field__c,Account_Credit_Limit_Field__c,Account_Joint_Commitees_Field__c,
            Account_Joint_Commitees_White_Field__c,Account_Legal_Form_Field__c,Account_Main_Activity_Field__c,Account_Number_Employees_Field__c,
            Account_Social_Security_Field__c,Account_Phone_Field__c,Account_Street_Field__c,Account_PostalCode_Field__c,Account_City_Field__c,Account_CountryCode_Field__c,
            Account_Annual_Revenue_Field__c,CW_Duplicate_Check_Creation__c,
            CW_Duplicate_Check_Refresh__c,Lead_Score_Field__c,Lead_Activities_Field__c,Lead_Credit_Limit_Field__c,Lead_Joint_Commitees_Field__c,
            Lead_Joint_Commitees_White_Field__c,Lead_Legal_Form_Field__c,Lead_Main_Activity_Field__c,Lead_Number_Employees_Field__c,Lead_Social_Security_Field__c,
            Lead_Phone_Field__c,Lead_Annual_Revenue_Field__c,Lead_Street_Field__c,Lead_PostalCode_Field__c,Lead_City_Field__c,Lead_CountryCode_Field__c
            FROM CW_Login_Setup__mdt WHERE DeveloperName = 'CW_Login'];
        connectCompanywebBe.RequestStep2 request = new connectCompanywebBe.RequestStep2();
        request.CompanyWebLogin = oLoginSetup.CW_CompanyWebLogin__c;
        request.CompanyWebPassword = oLoginSetup.CW_CompanyWebPassword__c;
        request.ServiceIntegrator = oLoginSetup.CW_ServiceIntegrator__c;
        request.LoginHash = companyWebController.createCWLoginHash(oLoginSetup.CW_CompanyWebLogin__c, oLoginSetup.CW_CompanyWebPassword__c, oLoginSetup.CW_CompanyWebSecret__c);
        request.ChangedDate = 20221113;
        request.Step2Token = 'tokenofnumbersandletters';
        connectCompanywebBe.BasicHttpBinding_AlacarteServiceV1_6_soap httpreq = new connectCompanywebBe.BasicHttpBinding_AlacarteServiceV1_6_soap();

        Test.setMock(WebServiceMock.class, new companyWebGetVatListCallOutMock());
        CompanyWebController.getVatList(httpreq, request);
    }
    
    @isTest
    public static void companyWebAlertsGetCompanyDataTest(){
        CW_Login_Setup__mdt oLoginSetup = new CW_Login_Setup__mdt();
        oLoginSetup = [SELECT Id, CW_CompanyWebLogin__c, CW_CompanyWebPassword__c, CW_CompanyWebSecret__c, CW_ServiceIntegrator__c, Account_VAT_Number_Field__c,
            Lead_VAT_Number_Field__c,Account_Score_Field__c,Account_Activities_Field__c,Account_Credit_Limit_Field__c,Account_Joint_Commitees_Field__c,
            Account_Joint_Commitees_White_Field__c,Account_Legal_Form_Field__c,Account_Main_Activity_Field__c,Account_Number_Employees_Field__c,
            Account_Social_Security_Field__c,Account_Phone_Field__c,Account_Street_Field__c,Account_PostalCode_Field__c,Account_City_Field__c,Account_CountryCode_Field__c,
            Account_Annual_Revenue_Field__c,CW_Duplicate_Check_Creation__c,
            CW_Duplicate_Check_Refresh__c,Lead_Score_Field__c,Lead_Activities_Field__c,Lead_Credit_Limit_Field__c,Lead_Joint_Commitees_Field__c,
            Lead_Joint_Commitees_White_Field__c,Lead_Legal_Form_Field__c,Lead_Main_Activity_Field__c,Lead_Number_Employees_Field__c,Lead_Social_Security_Field__c,
            Lead_Phone_Field__c,Lead_Annual_Revenue_Field__c,Lead_Street_Field__c,Lead_PostalCode_Field__c,Lead_City_Field__c,Lead_CountryCode_Field__c
            FROM CW_Login_Setup__mdt WHERE DeveloperName = 'CW_Login'];
        connectCompanywebBe.RequestStep3_CompanyOnVat request = new connectCompanywebBe.RequestStep3_CompanyOnVat();
        request.CompanyWebLogin = oLoginSetup.CW_CompanyWebLogin__c;
        request.CompanyWebPassword = oLoginSetup.CW_CompanyWebPassword__c;
        request.ServiceIntegrator = oLoginSetup.CW_ServiceIntegrator__c;
        request.LoginHash = companyWebController.createCWLoginHash(oLoginSetup.CW_CompanyWebLogin__c, oLoginSetup.CW_CompanyWebPassword__c, oLoginSetup.CW_CompanyWebSecret__c);
        request.Language = 'EN';
        request.VatNumber = '869703978';
        request.ChangedDate = 20221113;
        request.Step3Token = 'tokenofnumbersandletters';
        connectCompanywebBe.BasicHttpBinding_AlacarteServiceV1_6_soap httpreq = new connectCompanywebBe.BasicHttpBinding_AlacarteServiceV1_6_soap();

        List<Account> listOfAccountsToUpdate = [SELECT Id FROM Account];
        List<Lead> listOfLeadsToUpdate = [SELECT Id FROM Lead];

        Map<Integer, Map<Integer,String>> collectionOfStep3TokensByChangedDate = new Map<Integer,Map<Integer,String>>();
        Map<Integer,String> mapOfStep3Token = new Map<Integer,String>();
        mapOfStep3Token.put(869703978,'tokenofnumbersandletters');
        collectionOfStep3TokensByChangedDate.put(20221113,mapOfStep3Token);

        Test.setMock(WebServiceMock.class, new companyWebGetCompanyDataCallOutMock());
        System.enqueueJob(new companyWebCompanyByVATQueueable(httpreq, request, oLoginSetup, collectionOfStep3TokensByChangedDate, listOfAccountsToUpdate, listOfLeadsToUpdate));
    }

    @isTest
    public static void companyWebSendEmailTest(){
        CompanyWebController.sendEmail('test method', 0, 'test method succeeded');
    }
    
}